#!/usr/bin/env python3
"""
Auto-generate event documentation from Rust contractevent structs and enforce
that every declared event has at least one .publish( call site.

Usage:
    python scripts/generate_event_docs.py            # generate docs + lint
    python scripts/generate_event_docs.py --check    # lint only (CI mode, exits 1 on violation)
    python scripts/generate_event_docs.py --write    # generate and write docs/EVENTS.md

CI integration — add to your events-sync step:
    python scripts/generate_event_docs.py --check
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
EVENTS_RS = REPO_ROOT / "contracts" / "raffle-instance" / "src" / "events.rs"
LIB_RS = REPO_ROOT / "contracts" / "raffle-instance" / "src" / "lib.rs"
EVENTS_MD = REPO_ROOT / "docs" / "EVENTS.md"

# ---------------------------------------------------------------------------
# Parsing helpers
# ---------------------------------------------------------------------------

def parse_event_structs(events_path: Path) -> list[dict]:
    """
    Return a list of dicts for every #[contractevent] struct in events.rs:
        { name, fields: [(name, type)], topics: [name], doc: str }
    """
    text = events_path.read_text(encoding="utf-8")

    # Split on struct boundaries so we can associate doc comments with each struct.
    # Pattern: optional doc comments, #[contractevent], pub struct NAME { ... }
    pattern = re.compile(
        r'(?P<doc>(?:\s*///[^\n]*\n)*)'          # leading /// doc lines (optional)
        r'\s*#\[derive\(Clone\)\]\s*'
        r'#\[contractevent\]\s*'
        r'pub\s+struct\s+(?P<name>\w+)\s*\{'
        r'(?P<body>[^}]*)\}',
        re.DOTALL,
    )

    events = []
    for m in pattern.finditer(text):
        name = m.group("name")
        doc = re.sub(r'\s*///\s?', '', m.group("doc")).strip()
        body = m.group("body")

        fields = []
        topics = []
        for line in body.splitlines():
            line = line.strip()
            if not line or line.startswith("//"):
                continue
            if line == "#[topic]":
                # next field is a topic — track it
                topics.append("__next__")
                continue
            field_match = re.match(r'pub\s+(\w+)\s*:\s*(.+?),?\s*$', line)
            if field_match:
                fname, ftype = field_match.group(1), field_match.group(2).rstrip(",")
                if topics and topics[-1] == "__next__":
                    topics[-1] = fname
                fields.append((fname, ftype))

        events.append({"name": name, "fields": fields, "topics": topics, "doc": doc})

    return events


def find_publish_sites(search_root: Path) -> set[str]:
    """
    Return the set of event struct names that appear immediately before a
    .publish( call anywhere under search_root (*.rs files).
    """
    published = set()
    rs_files = list(search_root.rglob("*.rs"))
    for path in rs_files:
        text = path.read_text(encoding="utf-8")
        # Match:  EventName { ... } .publish(   or   EventName { ... }\n .publish(
        # We look for any word that is immediately followed (allowing whitespace)
        # by .publish( within the same expression.  A simpler heuristic: find
        # every struct literal construction whose identifier precedes .publish.
        for m in re.finditer(r'\b(\w+)\s*\{[^}]*\}\s*\n?\s*\.publish\s*\(', text, re.DOTALL):
            published.add(m.group(1))
    return published


# ---------------------------------------------------------------------------
# Lint check
# ---------------------------------------------------------------------------

def check_all_published(events: list[dict], published: set[str]) -> list[str]:
    """Return names of events that are declared but never published."""
    return [e["name"] for e in events if e["name"] not in published]


# ---------------------------------------------------------------------------
# Doc generation
# ---------------------------------------------------------------------------

def generate_events_md(events: list[dict]) -> str:
    lines = [
        "# Contract Events",
        "",
        "> Auto-generated by `scripts/generate_event_docs.py`. Do not edit manually.",
        "",
        "Each event is emitted via `.publish(&env)` on the Soroban contract.",
        "Fields marked **topic** are indexed and can be filtered by subscribers.",
        "",
    ]

    for ev in events:
        lines.append(f"## `{ev['name']}`")
        if ev["doc"]:
            lines.append("")
            lines.append(ev["doc"])
        lines.append("")
        lines.append("| Field | Type | Indexed |")
        lines.append("| ----- | ---- | ------- |")
        for fname, ftype in ev["fields"]:
            indexed = "✓" if fname in ev["topics"] else ""
            lines.append(f"| `{fname}` | `{ftype}` | {indexed} |")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    check_only = "--check" in sys.argv
    write_docs = "--write" in sys.argv

    if not EVENTS_RS.exists():
        print(f"ERROR: events.rs not found at {EVENTS_RS}", file=sys.stderr)
        return 1

    events = parse_event_structs(EVENTS_RS)
    published = find_publish_sites(REPO_ROOT / "contracts" / "raffle-instance" / "src")
    unpublished = check_all_published(events, published)

    print(f"Found {len(events)} declared events, {len(published)} with publish call sites.")

    if unpublished:
        print("\nERROR: The following events are declared but never published:", file=sys.stderr)
        for name in unpublished:
            print(f"  - {name}", file=sys.stderr)
        print(
            "\nFix: either emit the event with .publish(&env) or remove the struct from events.rs.",
            file=sys.stderr,
        )
        return 1

    print("OK: every declared event has at least one .publish() call site.")

    if check_only:
        return 0

    md = generate_events_md(events)

    if write_docs:
        EVENTS_MD.parent.mkdir(parents=True, exist_ok=True)
        EVENTS_MD.write_text(md, encoding="utf-8")
        print(f"Written: {EVENTS_MD}")
    else:
        print("\n" + md)

    return 0


if __name__ == "__main__":
    sys.exit(main())
